[build]
  command = "npm install --legacy-peer-deps --force && npm run build"
  publish = "dist"
  functions = "server/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["server/**/*.js", "server/**/*.json"] 